version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "terraform"
    directories:
      - "/terraform/global"
      - "/terraform/environments/dev"
      - "/terraform/environments/prod"
      - "/terraform/modules/static-website"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
